### ISSUE TITLE
Sense HAT interface

### ISSUE THREAD

**Issue by joelbieli** [joelbieli/pihoot#24]
**User Story**
As a user, I want to be able to play with a Sense HAT so that I have multiple options to play

**Acceptance Criteria**
- Given a Sense HAT is connected to the Raspberry PI when I try to play a game, then the controls are displayed on the LED matrix and the joystick can be used as input

**Story points**
8

**Subtasks**
- [x] Implement interface
- [x] Create GUI for LED matrix
- [ ] Hardware check script
- [ ] Take argument to run in Sense HAT mode
